name: Aditya Nair
markdown: kramdown
  
gems:
  - jekyll-seo-tag
title: Aditya Nair
description: Neuroscience Graduate Student at Caltech
author: Aditya Nair
social:
  name: Aditya Nair
  links:
    - https://twitter.com/adinairneuro
    - https://www.facebook.com/adityanairneuro
    - https://sg.linkedin.com/in/aditya-nair-680b6b74o
    - https://plus.google.com/114128390400853112123
    - https://github.com/adityanairneuro

gems:
  - jekyll-sitemap

theme: jekyll-theme-minimal
